#!/bin/csh -f

# GOAL:
#   bsview file.bs
#   - decodes and displays bitstream
#   -- decodes bitstream and puts it..? /tmp I guess...?
#   -- calls bsview.py file.bs-decoded

set scriptpath = $0
set scriptdir = ${scriptpath:h}
if ("$scriptpath" == "$scriptdir") set scriptdir = "."
set BSVIEW_HOME = $scriptdir

if ($#argv == 0) then
    USAGE:
    set sn = $scriptpath:t
    echo "Usage:"
    echo "    $sn <bitstream.bs>     # Decodes and displays bitstream"
    echo "    $sn -demo              # Runs through a couple built-in demos"
    echo "    $sn --help             # Displays this help message"
    exit 0
endif

if ("$argv[1]" == '--help') goto USAGE

if ("$argv[1]" == '-demo') then
  $BSVIEW_HOME/bsview.py
  exit 0
endif

# echo $BSVIEW_HOME/bsview.py $argv
# $BSVIEW_HOME/bsview.py $argv

# TODO maybe use extension to decide whether bs needs decoded or not
# or auto-detect

foreach bs ($argv)
  set bsname = $bs:t
  set bsdecoded = /tmp/$bsname-decoded
  echo "Decoding bitstream '$bs', output to '$bsdecoded'"

  echo "Before:"
  cat $bs
  
  echo
  echo "After:"
  $BSVIEW_HOME/../decoder/decode.py $bs | tee $bsdecoded

  echo "Decoded output is here: $bsdecoded"

  # echo -n "Continue? (^C to exit) "; set reply = $<; echo ""
  $BSVIEW_HOME/bsview.py $bsdecoded

end




